# Generated by Django 3.2.25 on 2026-02-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
